### ISSUE TITLE
Monitoring API change (or issue on client side)

### ISSUE THREAD

**Issue by Adanorm** [harlam357/hfm-net#304] opened 2020-04-09 09:08 UTC
Hello,

Please note that a new beta release of the fahclient 7.6.0 has been released.
Some issues on monitoring side, but certainly not on your side, but maybe work.

Missing data (for the moment what we saw) : 
- Version
- Username
- Team ID
- Slot Type

And note that now passwords are mandatory for monitoring.

**Comment by Adanorm** [comment] 2020-04-09 09:27
I contacted Stanford for quick feetback : https://github.com/FoldingAtHome/fah-control/issues/69

**Comment by harlam357** [comment] 2020-04-10 02:51
Looking at the public foldingathome.org and at foldingforum.org.  Don't see any news about v7.6.  I have beta team access, nothing there.  Where do I find this new client version?

**Comment by Adanorm** [comment] 2020-04-10 08:26
Hello Harlam,

Here :) https://foldingathome.org/beta/ 
Note that 7.6.1 is coming very soon.

**Comment by jcoffland** [comment] 2020-04-10 08:43
@harlam357 I took a look at the traffic between HFM and the new v7.6 beta and I cannot see anything wrong but users are reporting missing data in HFM.

FYI, Stanford is no longer involved with folding@home.

**Comment by Adanorm** [comment] 2020-04-10 15:02
Tested with 7.6.2, no improvement.

**Comment by jcoffland** [comment] 2020-04-11 06:17
The problem is that the info data blocks were reorganized in v7.6.x to include more information about the various libraries they client was built from.  The main goal of that change was to be able to see the exact git revisions the client was built from to the build can be reproduced.  This lead to creating separate info sections for each lib.

HFM currently expects there to be "Build" and "Folding@home Client" info blocks.  The info that was in these is now both contained in the "FAHClient" block.

I looked into to creating a PR for this but my .net foo is weak.

**Comment by ipkh** [comment] 2020-04-12 13:15
7.6.4 is out now in beta page.
7.6.3 says it -organize info blocks. In the changelog.
Try this one.

**Comment by Adanorm** [comment] 2020-04-14 10:16
Hello Harlam, 

Lots of things are fixed with 7.6.6. 

By the way, the XML generates this : <ClientVersion i:nil="true"/>
instead of something like this : <ClientVersion>7.6.6</ClientVersion>

I'm still checking but everything else is OK

**Comment by Adanorm** [comment] 2020-04-15 10:36
7.6.7 no improvement.

**Comment by Adanorm** [comment] 2020-04-16 13:50
Hello,

Same with 7.6.8

**Comment by harlam357** [comment] 2020-04-20 14:21
Hi Adanorm!  After talking with the FAHClient developer and looking at the way the data changed, we decided that I would handle the ClientVersion issue on my side.  I have that fixed in a development branch and will have a new build for you soon.

**Comment by Adanorm** [comment] 2020-04-20 14:43
I feel like a VIP :)

**Comment by Adanorm** [comment] 2020-04-22 08:31
Fixed on 0.9.13.1001

**Comment by harlam357** [comment] 2020-04-24 05:14
Fixed in master and will be released with 0.9.13

**Comment by harlam357** [comment] 2020-05-02 02:40
Scratch 0.9.14.  0.9.17 just went RTW.

**Closed by harlam357** 2020-05-02 02:40 UTC
Labels: enhancement
