### ISSUE TITLE
HFM Linux Clients: connection is not open.

### ISSUE THREAD

**Issue by atlbike** [harlam357/hfm-net#346] opened 2021-05-03 20:47 UTC
Updated HFM yesterday (5/2).
I've not been able to maintain a connection to any Linux clients, the other Win10 client is working correctly.
[5/3/2021-16:24:02] X (x9dr3-Lu2d) The connection is not open.
...
[5/3/2021-16:28:11] X (xeon-Lm1f) The connection is not open.
[5/3/2021-16:28:11] X System.InvalidOperationException: The connection is not open.
   at HFM.Client.FahClientCommand.<ExecuteAsync>d__10.MoveNext()

All of the Linux clients are Ubuntu or Mint 20, which had been working fine until the Win10 March updates.  
The FAH client remote connection works without issues.
Putty telnet connections also work without any noticeable issues.

HFM is able to control the slot, Pause/Fold, but data is not being updated.

**Comment by harlam357** [comment] 2021-05-03 20:54
Has this been working until you updated HFM on 5/2 or did it stop working after Windows 10 updates?

What version of HFM last worked?
What version of HFM did you update to on 5/2?

Please answer all three questions.

**Comment by atlbike** [comment] 2021-05-03 22:13
Previous ver: HFM O.9.21.1259.msi  installed last Sept.
Updated ver: HFM 0.9.22.1517.msi installed 5/3/21
I started having problems in March with intermittent erroneous PPD levels.
HFM had logged >27K WU, but I discontinued running HFM in early April due to PPD inaccuracy.

I deleted all three Linux clients from the current install.
I readded one client.
Connection passed test, but no client log files are available.

HFM log shows:
[5/3/2021-18:09:35] X (giga) The connection is not open.
[5/3/2021-18:09:35] X System.InvalidOperationException: The connection is not open.
   at HFM.Client.FahClientCommand.<ExecuteAsync>d__10.MoveNext()





________________________________

**Comment by harlam357** [comment] 2021-11-14 15:54
@atlbike Still an issue?  Tried the latest build?  I've tested connections to Linux clients myself and cannot reproduce, so I'd need more information to attempt to resolve the issue.

**Comment by atlbike** [comment] 2021-11-14 16:02
Thank you for following up on the issue.
I abandoned my folding effort in May, so I won't be able to test this release.

________________________________

**Comment by harlam357** [comment] 2024-01-01 18:16
Closing issue as cannot reproduce

**Closed by harlam357** 2024-01-01 18:16 UTC
Labels: help wanted, triaged
