### ISSUE TITLE
Suggestion - name of project and or link to it

### ISSUE THREAD

**Issue by hucker75** [harlam357/hfm-net#356] opened 2022-02-19 13:56 UTC
Currently the project column just says something like P18201, which is meaningless to me.  Could it either state a brief name (eg. "Cancer" or "Covid") and/or provide a link to the FAH page describing the project?

**Comment by harlam357** [comment] 2023-04-08 04:08
There is a link to the project available in the Tools > Benchmarks Viewer. 

![image](https://user-images.githubusercontent.com/13512136/230702134-1ea77c34-1e39-4e69-885d-39c5d8d1500f.png)

I think this is the first request I've had to surface the Project Cause in the UI. I'll have to see if that is available in the data provided by the client.

**Comment by harlam357** [comment] 2023-04-08 04:15
Duplicate of #342

**Closed by harlam357** 2023-04-08 04:15 UTC
Labels: duplicate, enhancement, triaged
