### ISSUE TITLE
Newly download projects are not sorted in the Points Calculator until restart

### ISSUE THREAD

**Issue by anand-bhat** [harlam357/hfm-net#307] opened 2020-04-20 12:49 UTC
~~Newly downloaded projects do not appear in the Points Calculator unless the program is restarted.~~

Newly downloaded projects are not sorted in the Points Calculator unless the program is restarted. Once added, they appear at the bottom of the picklist.

**Comment by harlam357** [comment] 2020-04-25 18:28
Can you provide some more detail?  I cannot reproduce.  If I simply close the Points Calculator and open it again, the new projects are there.  This is the expected behavior.  Here are my repro steps:

1) Tools > Points Calculator
2) Tools > Download Projects...
3) Drop down Points Calculator Projects combo box, newly downloaded projects will NOT be listed
4) Close Points Calculator
5) Tools > Points Calculator
6) Drop down Points Calculator Projects combo box, newly downloaded projects ARE listed

**Comment by anand-bhat** [comment] 2020-04-29 08:11
Sorry, this took a while. Here are the steps:

1. Observe that project P16439 missing in points calculator. This is a newly released project, long after HFM was opened on my system.
![image](https://user-images.githubusercontent.com/7332442/80574120-962a8680-8a44-11ea-9a1c-e32b5dc13b6f.png)

2. Sync projects from Stanford from HFM. Observe that p16439 was added.
![image](https://user-images.githubusercontent.com/7332442/80574161-ac384700-8a44-11ea-97d1-1ee7ab48cf73.png)

3. However, going back to the points calculator, p16439 is not shown in the picklist. The entry is definitely stored in the HFM database as the main windows (clients and slots) shows the calculated PPD.
![image](https://user-images.githubusercontent.com/7332442/80574202-bfe3ad80-8a44-11ea-9cf8-56e4fec15317.png)

**Comment by anand-bhat** [comment] 2020-04-29 08:13
Oh wait, I was too hasty. It appears the newly downloaded projects are added to the points calculator projects list. It's not inserted into the correct sequence and is added at the end of the list.

![image](https://user-images.githubusercontent.com/7332442/80574384-12bd6500-8a45-11ea-9ee9-52623abfc540.png)

**Comment by harlam357** [comment] 2020-05-02 05:08
So this appears to simply be a sorting issue?

**Comment by anand-bhat** [comment] 2020-05-02 05:09
Correct, the originally reported issue was an incorrect observation.

**Comment by harlam357** [comment] 2020-05-17 04:59
This is fixed in master and will be available in the next release.

**Closed** 2020-05-17 04:59 UTC
Labels: bug
